### ISSUE TITLE
Chat plugins cant mute the chat

### ISSUE THREAD

**Issue by xtomyserrax** [Guarmanda/FactionsUUIDChat#1]
AsyncPlayerChatEvent doesnt consider if this event was or not cancelled which makes impossible for other plugins to mute the chat.

**Comment by Guarmanda** [comment]
I hooked into essentials, so that essentials mute should work. But if you use another plugin, I can try to hook to it
Canceling the event was necessary for making the hover functionnality working, and for other little things (like people letting essentials Chat installed while trying to install chat plugins)

**Comment by xtomyserrax** [comment]
Just read this.

Well if you ignore cancelled events the issue would be fixed without the need to hook (just the other plugins need to have a lower priority than you do).

EasyClearChat doesnt have an API

**Comment by Guarmanda** [comment]
Should be fixed now. Added some features and fixed some things at the same time
